### ISSUE TITLE
simplify xml creation (binding file, name all simplType)

### ISSUE THREAD

**Issue by elvisbegovic** [qualipool/swissrets#110]
**Problem description**
Thanks to `schema.xsd`, we can generate classes in many languages.
We are using `xjc` for java, which result in:
![image](https://user-images.githubusercontent.com/2789203/66043389-496ae580-e51f-11e9-8768-3d2f0a0570e0.png)

Due to anonymous type like:
```
<xs:element name="development" minOccurs="0" maxOccurs="1">
  <xs:annotation>
	<xs:documentation>The development state of the property.</xs:documentation>
  </xs:annotation>
  <xs:simpleType>
	<xs:annotation />
	<xs:restriction base="xs:string">
	  <xs:enumeration value="full" />
	  <xs:enumeration value="partial" />
	  <xs:enumeration value="undeveloped" />
	</xs:restriction>
  </xs:simpleType>
</xs:element>
```
this element have `String` type created `protected String development;` while it only accept enum values `full,partial,undeveloped`

**Desired Solution**

How can we reduce this complexity for endusers(developer) and help 3th party lib like `xjc/xsd.exe` to guess/generate correct type?
What about name all simpleType in xsd? add binding file helper? 

What you think ?

**Comment by jensstalder** [comment]
If you find a way to create a PR to solve your specific case please go ahead and create a PR. Does make sense to use enums where possible. It might be a challenge since xml 1.1 might not support this. But feel free to contribute.

It also sounds like it could be you generator at fault. 

Maybe this can help you: https://www.w3schools.com/xml/schema_facets.asp

Feel free to reopen if you wisch to continue this.
