### ISSUE TITLE
urbanhome is requesting to reinstate the categories “plot=bauland” und “parking=parkplatz”

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#114]
**Problem description**
urbanhome is requesting to reinstate the categories `plot=bauland` und `parking=parkplatz`

**Desired Solution**
re-add `plot` and `parking-space|parking-possibility` or similar.

**Comment by jaggli** [comment]
Why?

**Comment by jensstalder** [comment]
These categories are actually used quite a bit already (CasaXML and IDX). Im guessing the elimination was unintentional during the SwissRETS transition.

**Comment by jensstalder** [comment]
This will be discused in more detail in a seperate Project-Proposal.

**Comment by koffeinfrei** [comment]
Found the related https://github.com/qualipool/swissrets/issues/86 which states that these 2 are covered by https://swissrets.ch/Utilizations.html.

**Comment by jensstalder** [comment]
Thanks @koffeinfrei still think this is not canon to the other categories.

To illustrate

| Utility        | Category           | Description DE / IDX  |
| ------------- |:-------------:| -----:|
| residential  | appartment |  |
| industrial      | factory      |    |
| parking | **~~parking-space~~**      |    |
| construction | **~~plot~~**      |  Building land   |
| agricultural | **~~plot~~**      |  Agricultural land   |

In other words intuitively there should still be a explicit category. interpreting utility=construction to be Building land is a bit of a stretch. The parking situation is something I guess we dropped specificity because it was rarely used.

Being explicit and not making such default assumptions would make the following also sensible/possible in the future for example?

| Utility        | Category           | Description DE / IDX  |
| ------------- |:-------------:| -----:|
| construction | house     |  Old dilapidated house which should be reconstructed  |
| parking | **~~boat-space~~**      |  Original category if it makes a comeback for some reason  |

**Comment by machss** [comment]
As @ThomasBietenhader remarked [in this PR](https://github.com/qualipool/swissrets/issues/86).
> How can the type of parking be communicated? I've used the according values in the characteristics element. But this does not feel right.

I'd second his concerns regarding the leck of parking categories.

The [category usage sheet](https://docs.google.com/spreadsheets/d/1NKx8oDF16AMF8nMXmaa4OQTC0iu9NdDPB2rN1pCa2vA/edit#gid=0) reveals, that at least `open slot` and `underground parking` are in use. One might argue it could be worth having categories for `covered slot` (and `covered parking place bike`, `outdoor parking place bike`) as well.

To reproduce these categories by analyzing the `characteristics` is quite cumbersome and even not resolvable in some circumstances: As [described here](https://docs.google.com/spreadsheets/d/1NKx8oDF16AMF8nMXmaa4OQTC0iu9NdDPB2rN1pCa2vA/edit#gid=1387607905) 

Utilization | Characteristics | Target Category
------------ | ------------- | -------------
parking | isUnderRoof=does-not-apply | open slot
parking | isUnderRoof=applies | covered slot
parking | hasGarage=applies | single garage

Since `Applicable` is not a boolean but consists of `applies`, `does-not-apply` and `unknown`, it is not obvious how to map, for instance, `parking + hasGarage=applies`.

Is it `single garage`? It could be `open slot`, too, since `isUnderRoof` is neither `true` nor `false`. 

Considering the case that there might be even more parking characteristics provided at once, the detection is not simply feasible.

**Comment by jensstalder** [comment]
So if I understand us three correctly we are talking about re-adding the following categories?

* plot
* parking-spot (Took the liberty of renaming ^^)
* underground-parking-spot
* covered-parking-spot

**Comment by machss** [comment]
@jensstalder That would be great :+1:
