### ISSUE TITLE
export -> properties -> property should be minOccurs=0

### ISSUE THREAD

**Issue by merrycoder** [qualipool/swissrets#116]
**Problem description**
It should be possible to create an empty importfile to remove all properties of a given owner from a platform. This is currently possible with IDX.

**Desired Solution**
Make export -> properties -> property minOccurs=0 instead of minOccurs=1

**Comment by jensstalder** [comment]
Thats correct that was in the original implementation. Its important that `<properties />` is present however, this would represent a empty delivery.

aka. 

```xml
<export>
   <projects></projects>
</export>
```
Would delete all projects but would leave properties alone. This will make possible seperation of project and property (or some other future resources) delivery in the future possible.

```xml
<export>
   <properties></properties>
</export>
```
Would delete all the properties

```xml
<export>
</export>
```
Would do nothing.

What do you think? This would probably be the result in having minOccurs=0 instead of =1 .
