### ISSUE TITLE
Validation for phone numbers

### ISSUE THREAD

**Issue by stefan-landgraf-is24** [qualipool/swissrets#68]
**Is your feature request related to a problem? Please describe.**
IDX showed, that phone numbers often come with invalid formats (e.g. containing texts)

**Describe the solution you'd like**
Introduce XSD validation for phone numbers. Suggestion: Only numeric values, space and + are allowed.

**Comment by jaggli** [comment]
Stefan and I discussed this and came up with this draft, what do you think? 
@jensstalder @adi-de-masi ?
```
<xs:simpleType name="phoneNumber">
  <xs:restriction base="xs:string">
    <xs:pattern value="^[+]?[0-9]+$"/>
  </xs:restriction>
</xs:simpleType>
```

**Comment by jensstalder** [comment]
Well, let's see. I went down this Rabithole before and every pattern I created created difficulties down the road. It's probably easier to leave presentation and storage conversions to the consumer. There are a near infinite amount of "correct" patterns. I think validating this will make life more difficult than it helps.

You can play around here:
https://regex101.com/r/PQXz5J/2

There are standards such as https://en.wikipedia.org/wiki/E.164 

A simpler validation thats just "numbers spaces and plusses allowed" would be more flexible, and easier to handle. We ended up presenting phonenumbers as they are provided on our portals, without trying to format them, because that created too many tickets.

**Comment by stefan-landgraf-is24** [comment]
@adi-de-masi 
This issue is not about fomatting, but about validation. i suppose we all agree, that we don't want texts or special chars in phone fields. so we need a dedicated type for phone numbers in the schema.

The formatting is a responsibility of the client. SwissRETS is purely for data transfer and the client will take care of formatting. and formatting is easiest, when the data comes in a strict and simple format.

**Comment by jaggli** [comment]
It's not about enforcing a "correct" pattern. The idea is, to **strip everything out beside of numbers and a leading + sign**. This way the place where the numbers are displayed can choose what format fit's them the most.
Do you think this is bad? If yes, why? @adi-de-masi @jensstalder

**Comment by adi-de-masi** [comment]
@stefan-landgraf-is24 Fair enough, it may be a request that isn't as important to us as for other stakeholders in this project. For me it would be important to clearly document the number format. I suggest to use the international version (meaning the + would be mandatory).

**Comment by jensstalder** [comment]
We are restricting something that I feel only makes things more difficult
later. Consider for instance, once letterings catches on (which is
commonplace in the us and other places) (for example 1800 COLLECT etc.) We
would need to loosen this restriction anyway. These conversions should be
the responsibility of the consumer (with consumer I mean for instance the
portal).

It makes generating the XML and the flexibility of the portal more
restricted. For instance you would force the portal into formating
telephone numbers because they are not human readable any-longer, where
with simple text fields that would not be necessary because the original
Person that entered the Phone number already made it human decision of
making it as readable as possible. The main purpose is presenting it within
Kontakt-Infos. It's trivial to convert it to other formats for different
uses (such as sms international formating) later.

I can assure you that this little change would cause immense backlash for
generators (softwares that need to now convert all phonenumbers) and
consumers (because they are requred to re-format them).

**Comment by jaggli** [comment]
I do not agree with the trivial part. A lot of people writing crazy formats (introduced by microsoft some time ago). Suff like
+41 (0) 76 324 55 55
+41 (076) 324 55 55
This makes it non-trivial for conversion into other formats.

**Comment by jensstalder** [comment]
It's just a question of "where" that needs to be dictated. I'm all for a more standardised world, but for some things its difficult to find a common solution for, especially when you need to consider international numbers, or local "traditional" ways of writing phone numbers with dashes and apostrophe and other weird ways that are in real use in Switzerland today.
Thats why I would suggest lossening the regex to allow spaces at least. That should not impact their usefulness (I would however disallow "()" to avoid the zero prefix confusion.). And we would need to revisit this once letter based phone numbers catch on ;-). We need to make lives easier also for something as simple as a Website, and not only for our benefit, where we will re-format the numbers to something common anyhow and would love to have some sort of strict or even machine format.

**Comment by stefan-landgraf-is24** [comment]
We store phone numbers like "+41-788254689" in the DB. I could live with "+41-78 825 46 89" also. can we agree on that format?

**Comment by jaggli** [comment]
Yes I think we can live with spaces, no dashes, because this is totally IS24 specific stuff.
Let me summarize it. we will:
- allow an optional leading +
- then numbers only, but with optional spaces in between the numbers
- at least 3 digits

Regex draft   
`^[+]?[0-9][0-9]+[0-9]$`

**Comment by stefan-landgraf-is24** [comment]
The dash is there, because international prefixes can have 1 to 3 digits which makes it difficult to determine the prefix . if we have a leading + we should have the dash also.

**Comment by jaggli** [comment]
implemented in `feature/refactoring`
