### ISSUE TITLE
Grannyflat vs Stöckli

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#8]
Granny flat != Stöckli
This is a misconception coming from IDX.

Also granny flat is not a category it's a feature.

Solution/Suggestion
======
add new category stoekli
remove category granny-flat
add feature is-granny-flat

**Comment by jaggli** [comment]
Note: i tried to find a better word in English. Turns out, there is no such word, so I guess we have to stick with stoeckli
- https://en.wikipedia.org/wiki/St%C3%B6ckli
- https://www.dict.cc/?s=st%C3%B6ckli
- https://en.langenscheidt.com/german-english/stoeckli#St%C3%B6ckli

We will:
- replace `granny-flat` with `stoeckli` in `property > categories -> category` enum
- add `property > characteristics > isGrannyFlat` and document it

Documentation for `isGrannyFlat`:  
"A single-family home, can be detached or attached to the other dwelling."

Do you agree @jensstalder ?

**Comment by jensstalder** [comment]
I agree that some very swiss terms (aka. very cultural terms) such as stöckli, will need to be preserves as is instead of trying to find internation equivalents such as granny-flat which does not quiet fit the description. I'm not sure if isGrannyFlat is needed within characteristics however. Would it be prudent to remove that term alltogether, I suspect it was only used in conjunction with stöckli.

**Comment by jaggli** [comment]
I'm totally fine with removing it. It's misleading.

We will:
- replace `granny-flat` with `stoeckli` in `property > categories -> category` enum
